heat_template_version: 2013-05-23

description: |
  A template that establishes Elastic Search, Logstash & Kibana

parameters:

  image:
    description: Rackspace Cloud Server Image (Distribution)
    type: string
    default: Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
    constraints:
    - allowed_values:
      - Ubuntu 14.04 LTS (Trusty Tahr) (PVHVM)
      description: Must be a valid Rackspace Cloud Server Image, default is Ubuntu 14.04 LTS (Trusty Tahr)

  branch:
    type: string
    default: master
    description: Repo branch to use
    constraints:
    - allowed_values:
      - master
      - dev
      description: Must be valid repo branch

resources:

  elk_server:
    type: "Rackspace::Cloud::Server"
    properties:
      flavor: 1 GB General Purpose v1
      image: { get_param: image }
      name: "elk"
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            apt-get update && apt-get install curl -y
            curl -skS -L https://raw.github.com/BigWhale/touchstone/%branch%/logging/server_userdata/elk.sh | sudo bash /dev/stdin %branch%
          params:
            "%branch%": { get_param: branch }

  rsyslog_server:
    type: "Rackspace::Cloud::Server"
    properties:
      flavor: 1 GB General Purpose v1
      image: { get_param: image }
      name: "rsyslog"
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            apt-get update && apt-get install curl -y
            curl -skS -L https://raw.github.com/BigWhale/touchstone/%branch%/logging/server_userdata/rsyslog_server.sh | sudo bash /dev/stdin %branch% %elk_server_ip%
          params:
            "%branch%": { get_param: branch }
            "%elk_server_ip%": { get_attr: [elk_server, privateIPv4] }

outputs:
  elk_public_ip:
    description: The public IP address of the ELK stack
    value: { get_attr: [elk_server, accessIPv4]}

